name: Build and Upload iOS App

on:
  push:
    branches:
      - master

env:
  REPO_NAME: "wonka-ios-spm-library-releases"
  REPO_OWNER: "PEER-Inc"
  REPO_BRANCH: "main"
  REPO_DIR: "wonka-sdk-build"
jobs:
  build_and_upload:
    runs-on:  macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build iOS app
        run: |
          pwd
          mkdir -p ${{ env.REPO_DIR }}
          
      - name: Notify Slack of build status
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Clean up build artifacts
        run: rm -rf ./build
