name: Manual Trigger Of The Release
on: 
  workflow_dispatch:
    inputs:
      Release_Branch:
        description: Branch on which the release process should be done    
        required: true
      Build_STORE:
        description: the build store or development (dev by default)    
        required: true
        default: dev
      Bump_VERSION:
        description: we bump patch, minor or major version (patch by default)    
        required: true

env:
  REPO_NAME: "ci-repo"
  REPO_OWNER: "ajaykumar1007"
  #REPO_BRANCH: "main"
  REPO_DIR: "wonka-sdk-build"

jobs:
  build_with_signing:
    runs-on: macos-latest
    steps:
      - name: Clone wonka-ios-spm-library-releases repository
        uses: actions/checkout@v3.0.2
        with:
          repository: ${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}
          ref: ${{ github.event.inputs.Release_Branch }}
          token: ${{ secrets.P_TOKEN }}
          path: ./archive-repo
      - name: Wonka SDK push in feature/wonka-ios-spm-library-releases repository
        working-directory: ./archive-repo
        env:
          token: ${{ secrets.ACCESS_TOKEN }}
        run: |
          ls -l
           pwd
