name: Manual Trigger Of The Release
on: 
  workflow_dispatch:
    inputs:
      Release_Branch:
        description: Branch on which the release process should be done    
        required: true
      Build_STORE:
        description: The build store or development (dev by default)    
        #default: dev
      Bump_VERSION:
        description: We bump patch, minor or major version (patch by default)    

env:
  REPO_NAME: "ci-repo"
  REPO_OWNER: "ajaykumar1007"
  #REPO_BRANCH: "main"
  REPO_DIR: "wonka-sdk-build"

jobs:
  build_with_signing:
    runs-on: macos-latest
    steps:
      - name: Clone wonka-ios-spm-library-releases repository
        uses: actions/checkout@v3.0.2
        with:
          repository: ${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}
          ref: ${{ github.event.inputs.Release_Branch }}
          token: ${{ secrets.P_TOKEN }}
          path: ./archive-repo
      - name: Wonka SDK push in feature/wonka-ios-spm-library-releases repository
        working-directory: ./archive-repo
        env:
          token: ${{ secrets.P_TOKEN }}
        run: |
          ls -l
          #python3 wonka_release_create_branch.py --bump-${{ github.event.inputs.Release_Branch }}-version
          #python3 wonka_release_build.py
          
      - name: Publish to GitHub not registry
        if: env.GITHUB_TOKEN != ''
        run: |
          echo "not"
          
      - name: Publish to GitHub find registry
        if: env.GITHUB_TOKEN == ''
        run: |
          echo "yes"
