name: Build and Upload iOS App

on:
  push:
    branches:
      - master

env:
  REPO_NAME: "wonka-ios-spm-library-releases"
  REPO_OWNER: "PEER-Inc"
  REPO_BRANCH: "main"
  REPO_DIR: "wonka-sdk-build"

jobs:
  build_and_upload:
    runs-on:  macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build iOS app
        run: |
          #xcodebuild -scheme MyProject -configuration Release clean build
          touch  tets12
          #docker ps
          # Sign the app with your code signing identity
          # Package the app with the necessary assets
          # Upload the app to the App Store using the App Store Connect API

      - uses: 8398a7/action-slack@v3
          with:
            status: ${{ job.status }}
            fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          if: always() # Pick up events even if the job fails or is canceled.

      - name: Clean up build artifacts
        run: rm -rf ./build
