name: Build and Upload iOS App

on:
  push:
    branches:
      - master
env:
  REPO_NAME: "ci-repo"
  REPO_OWNER: "ajaykumar1007"
  REPO_BRANCH: "main"
  REPO_DIR: "wonka-sdk-build"

jobs:
  build_and_upload:
    runs-on:  macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get tags
        run: git fetch --tags origin

      - name: Build iOS app
        run: |
          touch  ajay1233.txt 
          mkdir -p ${{ env.REPO_DIR }}
          cp ajay1233.txt ${{ env.REPO_DIR }}

      - name: Clone wonka-ios-spm-library-releases repository
        uses: actions/checkout@v3.0.2
        with:
          repository: ${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}
          ref: ${{ env.REPO_BRANCH }}
          token: ${{ secrets.P_TOKEN }}
          path: ./archive-repo
         
      - name: Wonka SDK push in wonka-ios-spm-library-releases repository
        working-directory: ./archive-repo
        env:
          token: ${{ secrets.P_TOKEN }}
        run: |
            #rm -rf Sources/*
            cp -r ../${{ env.REPO_DIR }}/* .
            ls -l
            pip3 install gitpython
            python3 ../a.py

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
            working-directory: ./archive-repo
            status: ${{ job.status }}
            fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() 

      - name: Clean up build artifacts
        run: rm -rf ./build
