name: Build and Upload iOS App

on:
  push:
    branches:
      - master

env:
  REPO_NAME: "ci-repo"
  REPO_OWNER: "ajaykumar1007"
  REPO_BRANCH: "main"
  REPO_DIR: "wonka-sdk-build"

jobs:
  build_and_upload:
    runs-on:  macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build iOS app
        run: |
          touch  tets12
          mkdir -p ${{ env.REPO_DIR }}
          cp tets12 ${{ env.REPO_DIR }}
          rm -rf .git*


      - name: Clone wonka-ios-spm-library-releases repository
        uses: actions/checkout@v3.0.2
        with:
          repository: ${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}
          ref: ${{ env.REPO_BRANCH }}
          token: ${{ secrets.P_TOKEN }}
          path: archive-repo

      - name: Git add and commit
        run: |
            cp -r ${{ env.REPO_DIR }}/* archive-repo/
            cd archive-repo/
            pwd
            git branch
            git add .
            git commit -m "Update to version"
            git tag 0.0.4
            git push origin 0.0.4



      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          title: "Update to v4.0.0"
          commit-message: "Bump version to v4.0.0"
          body: "This pull request updates the version to v4.0.0"
          base: "0.0.4"
          head: "release/v1.0.0"
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.P_TOKEN }}

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() 

      - name: Clean up build artifacts
        run: rm -rf ./build
