name: Build and Upload iOS App

on:
  push:
    branches:
      - master

env:
  REPO_NAME: "test-repo"
  REPO_OWNER: "ajaykumar1007"
  REPO_BRANCH: "0.0.3"
  REPO_DIR: "ios-build"
  APP_VERSION: "1.0.0"

jobs:
  build_and_upload:
    runs-on:  macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Build iOS app
        run: |
          pwd
          mkdir -p ${{ env.REPO_DIR }}
          echo "asvhgv haghf">test.txt
          git branch
          ls -l
          mv test.txt ${{ env.REPO_DIR }}
          echo "******************* fist setup************************************"
          ls -l ${{ env.REPO_DIR }}
          echo "************2nd step ***************"
          pwd
      - name: Clone archive repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}
          ref: ${{ env.REPO_BRANCH }}
          path: archive-repo

      - name: Copy iOS build to archive repository
        run: |
          ls -l
          pwd
          cp -r ${{ env.REPO_DIR }}/* archive-repo/
          echo "***************3rd****************************"
          ls -l
          pwd
          cd archive-repo
          echo "*****************4th step****************************"
          pwd
          ls -l
          git branch -a
          
          #git config --global user.email "actions@github.com"
          #git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add iOS build v${{ env.APP_VERSION }}"
          #git push

      - name: Clean up build artifacts
        run: rm -rf ./build
