name: Build and Upload iOS App

on:
  push:
    branches:
      - master

env:
  REPO_NAME: "ci-repo"
  REPO_OWNER: "ajaykumar1007"
  REPO_BRANCH: "main"
  REPO_DIR: "wonka-sdk-build"

jobs:
  build_and_upload:
    runs-on:  macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build iOS app
        run: |
          touch  tets1266565
          mkdir -p ${{ env.REPO_DIR }}
          cp tets1266565 ${{ env.REPO_DIR }}
          rm -rf .git*


      - name: Clone wonka-ios-spm-library-releases repository
        uses: actions/checkout@v3.0.2
        with:
          repository: ${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}
          ref: ${{ env.REPO_BRANCH }}
          token: ${{ secrets.P_TOKEN }}
          path: ./archive-repo
         
      - name: clone test
        working-directory: ./archive-repo
        env:
          token: ${{ secrets.P_TOKEN }}
        run: |
            cp -r ../${{ env.REPO_DIR }}/* .
            git status
            #git describe --tags $((git rev-list --tags --max-count=1))
            git branch
            git add .
            git commit -m "Update to version"
            git tag 0.0.7
            git push origin 0.0.7

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          path: ./archive-repo
          token: ${{ secrets.P_TOKEN }}
          title: "Update to v8.0.0"
          repository: ${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}
          #draft: true

#           commit-message: "Bump version to v4.0.0"
#           body: "This pull request updates the version to v5.0.0"
#           base: "main"
#           head: "release/v1.0.0"
#           draft: true
#         env:
#           GITHUB_TOKEN: ${{ secrets.P_TOKEN }}

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() 

      - name: Clean up build artifacts
        run: rm -rf ./build
